# .github/workflows/fetch-moph.yml
name: Fetch MOPH Data Daily

on:
  schedule:
    - cron: '0 1 * * *'  # ทุกวัน 08:00 น. ไทย (UTC+7 = 01:00 UTC)

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch MOPH and Save to Sheet
        run: |
          curl -s -X POST https://opendata.moph.go.th/api/report_data \
            -H "Content-Type: application/json" \
            -d '{"tableName":"s_childdev_specialpp","year":"2568","province":"42","type":"json"}' \
            -o response.json
          
          # ส่งไปให้ Apps Script
          curl -s -L -X POST "https://script.google.com/macros/s/AKfycbxYJTqOxb8Ff69LXftjZX5wkaNXiGLHrFXZdAbyp76HpzdfhetdUJ3TUybtoHzk_ttq/exec" \
            -H "Content-Type: application/json" \
            -d @response.json
